### ISSUE TITLE
Current syntax proposal fails to allow or disallow various necessary productions

### ISSUE THREAD

**Issue by efaust** [tc39/proposal-ptc-syntax#10]
The current PTC spec says that it's not a tail call to make a call that would otherwise be in tail position inside
- try blocks
- catch blocks
- for-in loops
- for-of loops

There is currently nothing in the stc proposal that forbids return continue in these places.

Further, the current spec allows

``` js
a || b()
```

to be in tail position, which we do not allow.

I think the dream of using a grammar parameter might be over. We either need to wind [ReturnExpr] all the way through _StatementList_ and into _TryStatement_, or to just add Static Semantics sections to further clarify. However, using those sections to refine the current grammar is somewhat misleading. I guess there is already precedent for this kind of thing.

**Comment by littledan** [comment]
These issues are all fixed in the current revision.
